sudo: required
services:
  - docker

before_install:
  - docker build -t vonghoangvinh1989/docker-react -f Dockerfile.dev .

script:
  - docker run vonghoangvinh1989/docker-react npm run test -- --coverage